default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: <%= ENV['DB_HOST'] %> # Optional, if you're using a separate DB host value.

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Use 'url' for the full DB connection string.

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Use 'url' for the full DB connection string.

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # This will get the Heroku DB URL from ENV.
  pool: 5
  timeout: 5000
  sslmode: require
